### ISSUE TITLE
Javascript undefined error preventing talk transcription

### ISSUE THREAD

**Issue by tsauvajon** [bitcointranscripts/bitcointranscripts#543]
After claiming a talk (id: 342), I see the talk both in "Current" and "Past" jobs:
<img width="1349" alt="image" src="https://github.com/user-attachments/assets/32bfaf13-1a23-456d-9a47-b45e216f139d">

Note that I claimed it just a few minutes ago.
And when trying to edit the transcript, I get a consistent `Application error: a client-side exception has occurred (see the browser console for more information).` without extra context, reproducible on different machines, different browsers, without adblockers etc.

<img width="709" alt="image" src="https://github.com/user-attachments/assets/13c74182-7651-42b5-8bc2-78f78623153e">

Errors in the console:
```
framework-18c7e6fcf99e5daa.js:9 TypeError: Cannot read properties of undefined (reading 'length')
    at [id]-46ce2bc37bdaa608.js:1:17850
    at ef ([id]-46ce2bc37bdaa608.js:1:17985)
    at ab (framework-18c7e6fcf99e5daa.js:9:60870)
    at i (framework-18c7e6fcf99e5daa.js:9:119410)
    at oO (framework-18c7e6fcf99e5daa.js:9:99059)
    at framework-18c7e6fcf99e5daa.js:9:98926
    at oF (framework-18c7e6fcf99e5daa.js:9:98933)
    at ox (framework-18c7e6fcf99e5daa.js:9:95685)
    at oC (framework-18c7e6fcf99e5daa.js:9:96074)
    at r4 (framework-18c7e6fcf99e5daa.js:9:44770)
a5 @ framework-18c7e6fcf99e5daa.js:9Understand this error
main-2f7be5f724b5184c.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at [id]-46ce2bc37bdaa608.js:1:17850
    at ef ([id]-46ce2bc37bdaa608.js:1:17985)
    at ab (framework-18c7e6fcf99e5daa.js:9:60870)
    at i (framework-18c7e6fcf99e5daa.js:9:119410)
    at oO (framework-18c7e6fcf99e5daa.js:9:99059)
    at framework-18c7e6fcf99e5daa.js:9:98926
    at oF (framework-18c7e6fcf99e5daa.js:9:98933)
    at ox (framework-18c7e6fcf99e5daa.js:9:95685)
    at oC (framework-18c7e6fcf99e5daa.js:9:96074)
    at r4 (framework-18c7e6fcf99e5daa.js:9:44770)
K @ main-2f7be5f724b5184c.js:1Understand this error
main-2f7be5f724b5184c.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-2f7be5f724b5184c.js:1Understand this error
framework-18c7e6fcf99e5daa.js:9 TypeError: Cannot read properties of undefined (reading 'length')
    at [id]-46ce2bc37bdaa608.js:1:17850
    at ef ([id]-46ce2bc37bdaa608.js:1:17985)
    at ab (framework-18c7e6fcf99e5daa.js:9:60870)
    at i (framework-18c7e6fcf99e5daa.js:9:119410)
    at oO (framework-18c7e6fcf99e5daa.js:9:99059)
    at framework-18c7e6fcf99e5daa.js:9:98926
    at oF (framework-18c7e6fcf99e5daa.js:9:98933)
    at ox (framework-18c7e6fcf99e5daa.js:9:95685)
    at oS (framework-18c7e6fcf99e5daa.js:9:94240)
    at x (framework-18c7e6fcf99e5daa.js:33:1364)
a5 @ framework-18c7e6fcf99e5daa.js:9Understand this error
main-2f7be5f724b5184c.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at [id]-46ce2bc37bdaa608.js:1:17850
    at ef ([id]-46ce2bc37bdaa608.js:1:17985)
    at ab (framework-18c7e6fcf99e5daa.js:9:60870)
    at i (framework-18c7e6fcf99e5daa.js:9:119410)
    at oO (framework-18c7e6fcf99e5daa.js:9:99059)
    at framework-18c7e6fcf99e5daa.js:9:98926
    at oF (framework-18c7e6fcf99e5daa.js:9:98933)
    at ox (framework-18c7e6fcf99e5daa.js:9:95685)
    at oS (framework-18c7e6fcf99e5daa.js:9:94240)
    at x (framework-18c7e6fcf99e5daa.js:33:1364)
K @ main-2f7be5f724b5184c.js:1Understand this error
main-2f7be5f724b5184c.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

**Comment by kouloumos** [comment]
Thanks for reaching out @tsauvajon!

We already have a fix ready for your second issue: https://github.com/bitcointranscripts/transcription-review-front-end/pull/301

We are already aware of the first issue, another user has already reported it: https://github.com/bitcointranscripts/bitcointranscripts/issues/537

**Comment by tsauvajon** [comment]
Thanks, closing in that case
